
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Riat Rayendra  ## put your name
title: 'NETWORK ADNIMISTRATOR &amp; TESTING'  ## your title
location: Pekanbaru , RIAU


## Social Profiles
facebook: http://www.facebook.com/RiatRayendra  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
